default_agent: agentcore_starter_strands
agents:
  agentcore_starter_strands:
    name: agentcore_starter_strands
    entrypoint: agentcore_starter_strands.py
    platform: linux/arm64
    container_runtime: none
    source_path: .
    aws:
      execution_role: arn:aws:iam::800622328366:role/AmazonBedrockAgentCoreSDKRuntime-eu-central-1-9c0804ec0c
      execution_role_auto_create: false
      account: '800622328366'
      region: eu-central-1
      ecr_repository: 800622328366.dkr.ecr.eu-central-1.amazonaws.com/bedrock-agentcore-agentcore_starter_strands
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: agentcore_starter_strands-V5kqR7Ap5a
      agent_arn: arn:aws:bedrock-agentcore:eu-central-1:800622328366:runtime/agentcore_starter_strands-V5kqR7Ap5a
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-agentcore_starter_strands-builder
      execution_role: arn:aws:iam::800622328366:role/AmazonBedrockAgentCoreSDKCodeBuild-eu-central-1-9c0804ec0c
      source_bucket: bedrock-agentcore-codebuild-sources-800622328366-eu-central-1
    memory:
      mode: STM_ONLY
      memory_id: agentcore_starter_strands_mem-8PXB31CZOq
      memory_arn: arn:aws:bedrock-agentcore:eu-central-1:800622328366:memory/agentcore_starter_strands_mem-8PXB31CZOq
      memory_name: agentcore_starter_strands_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
